# Generated by Django 2.2.14 on 2021-06-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_auto_20210602_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
