# Generated by Django 2.2.14 on 2021-06-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_auto_20210602_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='users/%Y/%m/%d/'),
        ),
    ]
