# Generated by Django 2.2.14 on 2021-06-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_auto_20210606_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='slug',
        ),
    ]
