# Generated by Django 2.2.14 on 2021-06-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_orderitem_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
